apiVersion: v1
kind: Pod
metadata:
  name: alerting
  labels:
    app: alerting
spec:
  containers:
    - image: lukesmolo/public:birex-alerting_0.0.4
      name: birex-alerting
      env:
      - name: PROCESS_URL
        value: "http://birex-processor:3000"
      - name: INTERVAL
        value: "3000"
      ports:
        - containerPort: 3001
