apiVersion: v1
kind: Pod
metadata:
  name: processor
  labels:
    app: processor
spec:
  containers:
    - image: lukesmolo/public:birex-process_0.0.1
      name: birex-processor
      env:
      - name: COLLECTOR_URL
        value: "http://birex-collector:8080/birexcollector"
      ports:
      - containerPort: 3000
ubuntu@control1:~/birex_orchestrator/edge-server/servizi-luca$ cat collector.yaml
apiVersion: v1
kind: Pod
metadata:
  name: collector
  labels:
    app: collector
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: zone
                operator: In
                values:
                  - edge
  containers:
    - image: lukesmolo/public:birex-collector_0.0.2
      name: birex-collector
