apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
  labels:
    app: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
        - image: lorenzobacchiani/edge
          name: edge
          ports:
            - containerPort: 8080
