apiVersion: v1
kind: Pod
metadata:
  name: edge
  labels:
    app: edge
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: zone
                operator: In
                values:
                  - edge
  containers:
    - image: lorenzobacchiani/edge
      name: edge
      ports:
        - containerPort: 8080
