apiVersion: v1
kind: Pod
metadata:
  name: multiple_orchestrator
  labels:
    app: orchestrator
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: zone
                operator: In
                values:
                  - cloud
  containers:
    - image: lorenzobacchiani/birex_multiple_orchestrator
      name: birex-orchestrator
      ports:
        - containerPort: 8081
