apiVersion: v1
kind: Pod
metadata:
  name: collector-3
  labels:
    app: collector-3
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: zone
                operator: In
                values:
                  - edge
  containers:
    - image: lukesmolo/public:birex-collector_0.0.5
      name: birex-collector
