apiVersion: v1
kind: Pod
metadata:
  name: generator
  labels:
    app: generator
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: zone
                operator: In
                values:
                  - edge
  containers:
    - image: lukesmolo/public:birex-simulator_0.0.2
      name: birex-simulator
      env:
      - name: USERNAME
        value: "birex"
      - name: PASSWORD
        value: "birex2.4"
      ports:
        - containerPort: 5050
